name: Github Action for React App

on: 
  push:
    branches:
       - "main"   # on which branch we need to push it

jobs:
 build: 
   runs-on: ubuntu-latest  # which os we want to run
   
   strategy:
    matrix: 
     node-version: [18.x] #node version required to build

   steps:
    - uses: actions/checkout@v3
    - run: npm install   # to download all dependecies
    - run: npm run build  # to build the app
    - run: npm test   # for unint test case checking
    
    # script to deploy the build in S3 bucket

    - uses: 99North/Snap-Shot-Project@main
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        # R_KEEP_PKG_SOURCE: yes
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # here the default region is set to us-east-1
        SOURCE_DIR: 'build'     #directory name to store the files






